---
title: "clean-data"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(skimr)

sheets <- excel_sheets(here::here("data","hackathon_20180621.xlsx"))

streams <- map(sheets, ~read_xlsx(here::here("data","hackathon_20180621.xlsx"), sheet = .x)) %>% 
  set_names(tolower(sheets))

skim(streams$bacteria)

```

Let's find the sites

string_trim

```{r}

site_locations <- str_split(streams$sitelist$`Geographic Coordinates (Decimal Degrees)`,",", simplify = T) %>% 
  as_data_frame() %>% 
  map_df(~str_replace(.x," ",""))  %>% 
  purrrlyr::dmap_if(is.character, as.numeric) %>% 
  set_names("longitude","latitude")


streams$sitelist <- streams$sitelist %>% 
  bind_cols(site_locations)

# ggmap::qmplot(longitude, latitude, data = streams$sitelist)


```


```{r}

chemistry <- streams$chemistry %>% 
  mutate(ParameterCode = tolower(ParameterCode),
         StationID = toupper(StationID)) %>% 
  mutate(flag = case_when(
    Units == "Deg F" ~ "temp_units",
    ParameterCode == "temp" & Result > 40 ~ "temp_value",
    ParameterCode == "ph" & Result > 14 ~ "ph_wild",
    TRUE ~ "NA"
  )) %>% 
  # convert F to C (including numbers that seem too high to be c)
  mutate(Result = if_else(Units == "Def F" | Result > 40, (Result - 32) * (5/9), Result)) %>% 
  mutate(Result = ifelse(flag == "ph_wild", NA, Result))
  
chemistry %>% 
  ggplot(aes(Result, fill = ParameterCode)) + 
  geom_histogram() + 
  facet_wrap(~ParameterCode, scales = "free")

saveRDS(chemistry, file = here::here("processed_data","chemistry.RDS"))

```


```{r}

names <- streams$nutrients %>% 
  colnames() %>% 
  stringr::str_replace_all(" ","")

nutrients <- streams$nutrients %>% 
  set_names(names) %>% 
  mutate(ParameterCode = tolower(ParameterCode),
         StationID = toupper(StationID))  
   
  
nutrients%>% 
  ggplot(aes(Result, fill = ParameterCode)) + 
  geom_histogram() + 
  facet_wrap(~ParameterCode, scales = "free")

saveRDS(nutrients, file = here::here("processed_data","nutrients.RDS"))

```


```{r}

names <- streams$bacteria %>% 
  colnames() %>% 
  stringr::str_replace_all(" ","")

bacteria <- streams$bacteria %>% 
  set_names(names) %>% 
  mutate(ParameterCode = tolower(ParameterCode),
         StationID = toupper(StationID))  %>% 
  mutate(ParameterCode = ifelse(ParameterCode == "e. coil",
                               "e. coli",
                               ParameterCode)) %>% 
  filter(ParameterCode != "duplicate")

bacteria %>% 
  ggplot(aes(Result, fill = ParameterCode)) + 
  geom_histogram() + 
  facet_wrap(~ParameterCode, scales = "free")

saveRDS(bacteria, file = here::here("processed_data","bacteria.RDS"))

  #TODO: check that SampleType - RESULTS, Duplicate, Split are similar
  # group_by(StationID, ParameterCode, SampleDate, SampleCollectionTime) %>% 
  # count()

```


